Embedded Systems: Pinos
Pinos
HAL
Provides the core capabilities for system timer functions.
Functions
bool PIN_Check (PinID_typedef Id)
Reads the state of the pin which its Id was given.
void PIN_Dir (PinID_typedef Id, bool dir)
Sets the Direction of a pin which its Id was given, the Dir is also given.
void PIN_Set (PinID_typedef Id)
Sets the Set of given pin to 1.
void PIN_Clear (PinID_typedef port)
Sets the Reset of given pin to 1.
Detailed Description
Provides the core capabilities for system timer functions.
Function Documentation
PIN_Check()
bool PIN_Check (PinID_typedef Id)
Reads the state of the pin which its Id was given.
Parameters
Id Pin which is to be checked
Returns
the current state of the Pin given by parameter
Definition at line 15 of file pin.c.
Referenced by LED_GetState().
PIN_Clear()
void PIN_Clear (PinID_typedef port)
Sets the Reset of given pin to 1.
Parameters
port Pin which we wish to Reset
Definition at line 42 of file pin.c.
Referenced by LED_Off().
PIN_Dir()
void PIN_Dir (PinID_typedef Id, bool dir)
Sets the Direction of a pin which its Id was given, the Dir is also given.
Parameters
Id Pin which we wish to change direction
dir Direction to be put in given Pin
Definition at line 29 of file pin.c.
PIN_Set()
void PIN_Set (PinID_typedef Id)
Sets the Set of given pin to 1.
Parameters
Id Pin which we wish to Set
Definition at line 36 of file pin.c.
Referenced by LED_On().