Embedded Systems: ENCODER
ENCODER
DRIVERS
Provides the core capabilities for the Rotary Encoder Switch.
Functions
void ENCODER_Init (int rate)
Initializes the ENCODER.
int ENCODER_GetValue (void)
Reads the state of the built-in LED and returns its logical value.
ENCODER_ButtonValueType ENCODER_GetButton (void)
Reads the state of the click of the button.
void ENCODER_Handler (void)
Function that handles the ENCODER during interruptions.
int ReadValues (void)
Reads the state of the two bits that determine rotation.
Detailed Description
Provides the core capabilities for the Rotary Encoder Switch.
Function Documentation
ENCODER_GetButton()
ENCODER_ButtonValueType ENCODER_GetButton (void)
Reads the state of the click of the button.
Parameters
Does not have entry parameters
Returns
value of the button when it was called
Definition at line 112 of file ENCODER.c.
ENCODER_GetValue()
int ENCODER_GetValue (void)
Reads the state of the built-in LED and returns its logical value.
Parameters
Does not have entry parameters
Returns
the current state of the built-in LED
Note
this function must be used before any other ENCODER function
Definition at line 87 of file ENCODER.c.
ENCODER_Handler()
void ENCODER_Handler (void)
Function that handles the ENCODER during interruptions.
Parameters
Does not have entry parameters
Returns
none
Definition at line 30 of file ENCODER.c.
References PIN_Check().
Referenced by ENCODER_Init().
ENCODER_Init()
void ENCODER_Init (int rate)
Initializes the ENCODER.
Parameters
rate rate at which the encoder is going to work at
Returns
none
Definition at line 73 of file ENCODER.c.
References ENCODER_Handler(), PIN_settype(), RIT_SetHandler(), and RIT_Start().
ReadValues()
int ReadValues (void)
Reads the state of the two bits that determine rotation.
Parameters
Does not have entry parameters
Returns
the value of those 2 bits
Definition at line 151 of file ENCODER.c.
References PIN_Check().