Embedded Systems: SPI
SPI
HAL
Provides the core capabilities for the SPI.
Functions
void SPI_Init (void)
Initializes the SPI.
void SPI_ConfigTransfer (int bitData, int frequency, int mode)
Configures the SPI according to the entry parameters.
unsigned short SPI_Transfer (unsigned short value)
Transfers a word and receives a word.
Detailed Description
Provides the core capabilities for the SPI.
Function Documentation
SPI_ConfigTransfer()
void SPI_ConfigTransfer (int bitData, int frequency, int mode)
Configures the SPI according to the entry parameters.
Parameters
bitData : Number of bits given
frequency : Rhythm of reception and transmission
mode : Mode of Operation
Definition at line 31 of file spi.c.
Referenced by MFRC522_PreInit().
SPI_Init()
void SPI_Init (void)
Initializes the SPI.
Parameters
Does not have entry parameters
Note
This function must be called prior to any other SPI function
Definition at line 17 of file spi.c.
References PIN_settype().
Referenced by MFRC522_PreInit().
SPI_Transfer()
unsigned short SPI_Transfer (unsigned short value)
Transfers a word and receives a word.
Parameters
value The word to be sent
Returns
the word received
Definition at line 60 of file spi.c.
Referenced by MFRC522_Transfer().