Embedded Systems: TIMER
TIMER
HAL
Provides the core capabilities for system timer functions.
Functions
void RIT_ClockEnable (int position)
Enables the RIT clock.
uint32_t RITPWR_GetPClk (int position, int speed)
Powers up the RIT clock and gives it a given speed.
void RIT_SetHandler (int rateMillis, RIT_HandlerType handler)
Sets the handler that the RIT interrupts will run.
bool RIT_Start (void)
Starts the in-built RIT.
void RIT_Stop (void)
Stops the in-built RIT.
void RIT_Restart (void)
Restarts the in-built RIT.
void RIT_IRQHandler (void)
Handles the RIT interruptions.
void TIMER_StopwatchInit (void)
Initializes Timer0 in a microseconds resolution.
void TIMER_Stopwatch (uint32_t waitUs)
Waits the microseconds passed through parameter.
Detailed Description
Provides the core capabilities for system timer functions.
Function Documentation
RIT_ClockEnable()
void RIT_ClockEnable (int position)
Enables the RIT clock.
Parameters
position Receives the position of the bit that activated the RIT clock
Returns
the current state of the built-in LED
Definition at line 28 of file timer.c.
RIT_IRQHandler()
void RIT_IRQHandler (void)
Handles the RIT interruptions.
Parameters
Does not have entry parameters
Definition at line 61 of file timer.c.
RIT_Restart()
void RIT_Restart (void)
Restarts the in-built RIT.
Parameters
Does not have entry parameters
Definition at line 88 of file timer.c.
RIT_SetHandler()
void RIT_SetHandler (int rateMillis, RIT_HandlerType handler)
Sets the handler that the RIT interrupts will run.
Parameters
rateMillis Rate at which it interrupts
handler A RIT_HandlerType that will be the handler which runs in every interruption
Definition at line 48 of file timer.c.
Referenced by ENCODER_Init().
RIT_Start()
bool RIT_Start (void)
Starts the in-built RIT.
Parameters
Does not have entry parameters
Returns
the current state of the RIT
Definition at line 72 of file timer.c.
Referenced by ENCODER_Init().
RIT_Stop()
void RIT_Stop (void)
Stops the in-built RIT.
Parameters
Does not have entry parameters
Definition at line 82 of file timer.c.
RITPWR_GetPClk()
uint32_t RITPWR_GetPClk (int position, int speed)
Powers up the RIT clock and gives it a given speed.
Parameters
position Position of the bit to power up the RIT clock
speed (1,2,3,4) to decide which of the 4 possible speeds it powers the RIT clock
Returns
the speed at which the clock is running in Hz
Definition at line 32 of file timer.c.
TIMER_Stopwatch()
void TIMER_Stopwatch (uint32_t waitUs)
Waits the microseconds passed through parameter.
Parameters
waitUs Number of microseconds supposed to wait
Definition at line 118 of file timer.c.
Referenced by DELAY_Stopwatch().
TIMER_StopwatchInit()
void TIMER_StopwatchInit (void)
Initializes Timer0 in a microseconds resolution.
Parameters
Does not have entry parameters
Definition at line 95 of file timer.c.
Referenced by DELAY_StopwatchInit().