Embedded Systems: LED
LED
DRIVERS
Provides the core capabilities for the built-in LED.
Functions
void LED_Init (bool state)
Initializes the pin of the built-in LED as output and defines the initial state of the LED as given by the parameter.
bool LED_GetState (void)
Reads the state of the built-in LED and returns its logical value.
void LED_On (void)
Turns on the built-in LED.
void LED_Off (void)
Turns off the built-in LED.
void LED_Toggle (void)
Inverts the state of the built-in LED.
Detailed Description
Provides the core capabilities for the built-in LED.
Function Documentation
LED_GetState()
bool LED_GetState (void)
Reads the state of the built-in LED and returns its logical value.
Parameters
Does not have entry parameters
Returns
the current state of the built-in LED
Definition at line 27 of file LED.c.
References PIN_Check().
Referenced by LED_Toggle().
LED_Init()
void LED_Init (bool state)
Initializes the pin of the built-in LED as output and defines the initial state of the LED as given by the parameter.
Parameters
state state has the initial state of the built-in LED
Definition at line 16 of file LED.c.
LED_Off()
void LED_Off (void)
Turns off the built-in LED.
Parameters
Does not have entry parameters
Definition at line 37 of file LED.c.
References PIN_Clear().
Referenced by LED_Toggle().
LED_On()
void LED_On (void)
Turns on the built-in LED.
Parameters
Does not have entry parameters
Definition at line 32 of file LED.c.
References PIN_Set().
Referenced by LED_Toggle().
LED_Toggle()
void LED_Toggle (void)
Inverts the state of the built-in LED.
Parameters
Does not have entry parameters
Definition at line 42 of file LED.c.
References LED_GetState(), LED_Off(), and LED_On().