Embedded Systems: DELAY
DELAY
DRIVERS
Provides the core capabilities for time functionalities.
Functions
int DELAY_Init (void)
Initializes the SYSTICK counter using the SYSTICK API.
void DELAY_Milliseconds (uint32_t millis)
Utilizes the SYSTICK API to count a given number of ms given by the user.
uint32_t DELAY_GetElapsedMillis (uint32_t start)
Utilizes the SYSTICK API to find out the difference between the current counter of ms and the start parameter.
void DELAY_StopwatchInit (void)
Initializes the TIMER0 counter using the timer API.
void DELAY_Stopwatch (uint32_t waitUs)
Utilizes TIMER0 to count a given number of microseconds given by the user.
Detailed Description
Provides the core capabilities for time functionalities.
Function Documentation
DELAY_GetElapsedMillis()
uint32_t DELAY_GetElapsedMillis (uint32_t start)
Utilizes the SYSTICK API to find out the difference between the current counter of ms and the start parameter.
Parameters
start : number used to compare with the current timer
Definition at line 27 of file DELAY.c.
References SYSTICK_GetValue().
Referenced by setDate(), textCalendar(), and textClock().
DELAY_Init()
int DELAY_Init (void)
Initializes the SYSTICK counter using the SYSTICK API.
Parameters
Does not have entry parameters
Note
This function must be called prior to DELAY_Milliseconds and DELAY_GetElapsedMillis functions
Definition at line 14 of file DELAY.c.
References SYSTICK_Init().
DELAY_Milliseconds()
void DELAY_Milliseconds (uint32_t millis)
Utilizes the SYSTICK API to count a given number of ms given by the user.
Parameters
millis : number of milliseconds to count
Definition at line 19 of file DELAY.c.
References SYSTICK_GetValue().
DELAY_Stopwatch()
void DELAY_Stopwatch (uint32_t waitUs)
Utilizes TIMER0 to count a given number of microseconds given by the user.
Parameters
waitUs : number of microseconds to wait
Definition at line 39 of file DELAY.c.
References TIMER_Stopwatch().
Referenced by LCDText_Clear(), LCDText_Printf(), LCDText_WriteString(), and MFRC522_WaitMs().
DELAY_StopwatchInit()
void DELAY_StopwatchInit (void)
Initializes the TIMER0 counter using the timer API.
Parameters
Does not have entry parameters
Note
This function must be called prior to DELAY_Stopwatch function
Definition at line 33 of file DELAY.c.
References TIMER_StopwatchInit().