Embedded Systems: FLASH
FLASH
HAL
Provides the core capabilities for the non volatile memory (Flash).
Functions
void call_iap ()
Calls the IAP routine that is already stored in a given address of memory.
unsigned int FLASH_BlankCheck (unsigned int sector)
Runs the IAP routine with BlankCheck command (checks if the sector is blank)
unsigned int FLASH_PrepareSector (unsigned int sector)
Runs the IAP routine with PrepareSector command (prepares the sector for write operations)
unsigned int FLASH_EraseSector (unsigned int sector)
Runs the IAP routine with EraseSector command (erases the sector)
unsigned int FLASH_WriteData (void *dstAddr, void *srcAddr, unsigned int size)
Runs the IAP routine with WriteData command (writes what you want where you want)
unsigned int FLASH_VerifyData (void *dstAddr, void *srcAddr, unsigned int size)
Reads the state of the built-in LED and returns its logical value.
Detailed Description
Provides the core capabilities for the non volatile memory (Flash).
Provides the core capabilities for the non volatile memory built-in flash.
Function Documentation
call_iap()
void call_iap ()
Calls the IAP routine that is already stored in a given address of memory.
Parameters
Does not have entry parameters
Definition at line 19 of file flash.c.
FLASH_BlankCheck()
unsigned int FLASH_BlankCheck (unsigned int sector)
Runs the IAP routine with BlankCheck command (checks if the sector is blank)
Parameters
sector Sector in which you wish to run the BlankCheck command
Returns
the error code that the IAP routine gave
Definition at line 23 of file flash.c.
Referenced by DRIVERS_FLASH_BlankCheck().
FLASH_EraseSector()
unsigned int FLASH_EraseSector (unsigned int sector)
Runs the IAP routine with EraseSector command (erases the sector)
Parameters
sector Sector in which you wish to run the EraseSector command
Returns
the error code that the IAP routine gave
Definition at line 60 of file flash.c.
Referenced by DRIVERS_FLASH_EraseSector().
FLASH_PrepareSector()
unsigned int FLASH_PrepareSector (unsigned int sector)
Runs the IAP routine with PrepareSector command (prepares the sector for write operations)
Parameters
sector Sector in which you wish to run the PrepareSector command
Returns
the error code that the IAP routine gave
Note
this function must be run before any write operations in the flash
Definition at line 42 of file flash.c.
Referenced by DRIVERS_FLASH_PrepareSector().
FLASH_VerifyData()
unsigned int FLASH_VerifyData (void * dstAddr, void * srcAddr, unsigned int size)
Reads the state of the built-in LED and returns its logical value.
Parameters
*dstAddr Address of the destination where I wish to write
*srcAddr Address of the source of what I wish to write
size Size of what I wish to write
Returns
the error code that the IAP routine gave
Definition at line 98 of file flash.c.
Referenced by DRIVERS_FLASH_VerifyData().
FLASH_WriteData()
unsigned int FLASH_WriteData (void * dstAddr, void * srcAddr, unsigned int size)
Runs the IAP routine with WriteData command (writes what you want where you want)
Parameters
*dstAddr Address of the destination where I wish to write
*srcAddr Address of the source of what I wish to write
size Size of what I wish to write
Returns
the error code that the IAP routine gave
Definition at line 78 of file flash.c.
Referenced by DRIVERS_FLASH_WriteData().