Embedded Systems: PINS
PINS
HAL
Provides the core capabilities for GPIO.
Functions
bool PIN_Check (PinID_typedef id)
Reads the state of the pin which its Id was given.
void PIN_Dir (PinID_typedef id, bool dir)
Sets the Direction of a pin which its Id was given, the Dir is also given.
void PIN_Set (PinID_typedef id)
Sets the Set of given pin to 1.
void PIN_Clear (PinID_typedef id)
Sets the Reset of given pin to 1.
Detailed Description
Provides the core capabilities for GPIO.
Function Documentation
PIN_Check()
bool PIN_Check (PinID_typedef id)
Reads the state of the pin which its Id was given.
Parameters
id Pin which is to be checked
Returns
the current state of the Pin given by parameter
Definition at line 16 of file pin.c.
Referenced by ENCODER_Handler(), LED_GetState(), and ReadValues().
PIN_Clear()
void PIN_Clear (PinID_typedef id)
Sets the Reset of given pin to 1.
Parameters
id pin which we wish to Reset
Definition at line 43 of file pin.c.
Referenced by LED_Off(), MFRC522_Reset(), and MFRC522_Select().
PIN_Dir()
void PIN_Dir (PinID_typedef id, bool dir)
Sets the Direction of a pin which its Id was given, the Dir is also given.
Parameters
id Pin which we wish to change direction
dir Direction to be put in given Pin
Definition at line 30 of file pin.c.
PIN_Set()
void PIN_Set (PinID_typedef id)
Sets the Set of given pin to 1.
Parameters
id Pin which we wish to Set
Definition at line 37 of file pin.c.
Referenced by LED_On().