Embedded Systems: MODES
MODES
APP
Provides functions for the modes of the application.
Functions
void modoNormal (struct tm *dateTime)
Function that runs normal mode of the app.
void modoManutencao (struct tm *dateTime)
Function that runs maintenance mode of the app.
int isAuthorized (Uid uid)
Useful function to check if the read card is in the list of the authorized cards.
int isEqual (Uid uid)
Useful function to check if the read card is the one authorized to open the locker.
void addLogEntry (Uid card, int authStatus)
Function to add a log to the log structs array.
void displayLog (LogsType log)
Displays the log sent by parameter.
void removeCard (int selectedIndex)
Removes a card from the authCards struct array given by the index.
void addCard (uint8_t uidByte[10], uint8_t size)
Adds a card to the authCards struct.
void saveStartupStateToFlash (void)
Function to write the startup struct to the flash.
void loadStartupStateFromFlash (void)
Function to load the startup struct from the flash.
void loadStartup (void)
Loads the loaded struct into the correct global variables.
void saveStartup (void)
Saves the global variables into the startup struct.
Detailed Description
Provides functions for the modes of the application.
Function Documentation
addCard()
void addCard (uint8_t uidByte[10], uint8_t size)
Adds a card to the authCards struct.
Parameters
uidByte attribute that tells us the identification of the card
size size of the uidByte parameter (between 4,7,10)
Returns
none
Definition at line 614 of file modes.c.
References LCDText_Clear().
addLogEntry()
void addLogEntry (Uid card, int authStatus)
Function to add a log to the log structs array.
Parameters
card Card read that led to the creation of a log
authStatus authorized status of the card read
Returns
none
Definition at line 525 of file modes.c.
References RTC_GetValue().
displayLog()
void displayLog (LogsType log)
Displays the log sent by parameter.
Parameters
log log to display
Returns
none
Definition at line 581 of file modes.c.
References LCDText_Printf().
isAuthorized()
int isAuthorized (Uid uid)
Useful function to check if the read card is in the list of the authorized cards.
Parameters
uid struct where we keep the data of the read card
Returns
the value of the comparison
Definition at line 491 of file modes.c.
isEqual()
int isEqual (Uid uid)
Useful function to check if the read card is the one authorized to open the locker.
Parameters
uid struct where we keep the data of the read card
Returns
the value of the comparison
Definition at line 511 of file modes.c.
loadStartup()
void loadStartup (void)
Loads the loaded struct into the correct global variables.
Parameters
none
Returns
none
Definition at line 674 of file modes.c.
References loadStartupStateFromFlash().
loadStartupStateFromFlash()
void loadStartupStateFromFlash (void)
Function to load the startup struct from the flash.
Parameters
none
Returns
none
Definition at line 691 of file modes.c.
Referenced by loadStartup().
modoManutencao()
void modoManutencao (struct tm * dateTime)
Function that runs maintenance mode of the app.
Parameters
dateTime time struct that is given so the mode knows what is the current machine time
Returns
none
Definition at line 249 of file modes.c.
References LCDText_Clear(), and LCDText_Printf().
modoNormal()
void modoNormal (struct tm * dateTime)
Function that runs normal mode of the app.
Parameters
dateTime time struct that is given so the mode knows what is the current machine time
Returns
none
Definition at line 57 of file modes.c.
References LCDText_Clear(), and LCDText_Printf().
removeCard()
void removeCard (int selectedIndex)
Removes a card from the authCards struct array given by the index.
Parameters
selectedIndex index of the card to remove
Returns
none
Definition at line 595 of file modes.c.
saveStartup()
void saveStartup (void)
Saves the global variables into the startup struct.
Parameters
none
Returns
none
Definition at line 647 of file modes.c.
Referenced by saveStartupStateToFlash().
saveStartupStateToFlash()
void saveStartupStateToFlash (void)
Function to write the startup struct to the flash.
Parameters
none
Returns
none
Definition at line 657 of file modes.c.
References saveStartup().