Embedded Systems: DRIVERS_MFRC522
DRIVERS_MFRC522
DRIVERS
Provides the core capabilities for the MFRC522 using the in-built SPI.
Functions
void MFRC522_PreInit (void)
Does the needed initializations for the MFRC522.h library.
void MFRC522_Reset (bool assert)
Changes the pin of reset according to the value of assert.
void MFRC522_Select (bool assert)
Changes the select pin according to the value of assert.
uint8_t MFRC522_Transfer (uint8_t value)
Transfers an int of 8 bytes.
void MFRC522_WaitMs (uint32_t millis)
Waits miliseconds.
Detailed Description
Provides the core capabilities for the MFRC522 using the in-built SPI.
Function Documentation
MFRC522_PreInit()
void MFRC522_PreInit (void)
Does the needed initializations for the MFRC522.h library.
Parameters
Does not have entry parameters
Returns
none
Definition at line 12 of file DRIVERS_MFRC522.c.
References SPI_ConfigTransfer(), and SPI_Init().
MFRC522_Reset()
void MFRC522_Reset (bool assert)
Changes the pin of reset according to the value of assert.
Parameters
assert value to put in the reset pin
Returns
none
Definition at line 23 of file DRIVERS_MFRC522.c.
References PIN_Clear().
MFRC522_Select()
void MFRC522_Select (bool assert)
Changes the select pin according to the value of assert.
Parameters
assert value to put in the select pin
Returns
none
Definition at line 35 of file DRIVERS_MFRC522.c.
References PIN_Clear().
MFRC522_Transfer()
uint8_t MFRC522_Transfer (uint8_t value)
Transfers an int of 8 bytes.
Parameters
value value to be transferred
Returns
value that is transmited back
Definition at line 46 of file DRIVERS_MFRC522.c.
References SPI_Transfer().
MFRC522_WaitMs()
void MFRC522_WaitMs (uint32_t millis)
Waits miliseconds.
Parameters
millis milliseconds to be waited
Returns
none
Definition at line 53 of file DRIVERS_MFRC522.c.
References DELAY_Stopwatch().