Embedded Systems: SYSTICK
SYSTICK
HAL
Provides the core capabilities for system timer functions.
Functions
void SysTick_Handler (void)
Interruption Handler for SYSTICK.
int SYSTICK_Init (uint32_t value)
Initialises the systick API for 1 ms resolution.
uint32_t SYSTICK_GetValue (void)
Get current value of ticks.
Detailed Description
Provides the core capabilities for system timer functions.
Function Documentation
SYSTICK_GetValue()
uint32_t SYSTICK_GetValue (void)
Get current value of ticks.
Returns
Returns the current tick value in milliseconds.
Definition at line 29 of file SYSTICK.c.
Referenced by DELAY_GetElapsedMillis(), and DELAY_Milliseconds().
SysTick_Handler()
void SysTick_Handler (void)
Interruption Handler for SYSTICK.
Parameters
Does not have parameters of entry
Definition at line 17 of file SYSTICK.c.
SYSTICK_Init()
int SYSTICK_Init (uint32_t value)
Initialises the systick API for 1 ms resolution.
Parameters
value receices the value in ms of time to count
Returns
0 if initialisation successed; -1 if fails.
Note
This function must be called prior to any other SYSTICK functions, and use the SYSTICK resource.
Definition at line 22 of file SYSTICK.c.
Referenced by DELAY_Init().