Embedded Systems: RTC
RTC
DRIVERS
Provides the core capabilities for the built-in Real Time Clock.
Functions
void RTC_Init (time_t seconds)
Initializes the API for the RTC.
void RTC_GetValue (struct tm *dateTime)
Reads RTC's current value in the form of a date.
void RTC_SetValue (struct tm *dateTime)
Updates the RTC to the new values passed to it in the form of a date.
void RTC_SetSeconds (time_t seconds)
Updates the RTC to the new values passed to it in the form of seconds.
time_t RTC_GetSeconds (void)
Reads RTC's current value in the form of seconds since 1/1/1970, 00:00:00 UTC.
Detailed Description
Provides the core capabilities for the built-in Real Time Clock.
Function Documentation
RTC_GetSeconds()
time_t RTC_GetSeconds (void)
Reads RTC's current value in the form of seconds since 1/1/1970, 00:00:00 UTC.
Parameters
does not have any entry parameters
Returns
seconds: seconds since 1/1/1970, 00:00:00 UTC
Definition at line 34 of file RTC.c.
RTC_GetValue()
void RTC_GetValue (struct tm * dateTime)
Reads RTC's current value in the form of a date.
Parameters
dateTime pointer to the structure where the value of the date is stored
Definition at line 22 of file RTC.c.
References RTC_HalGetValue().
Referenced by addLogEntry().
RTC_Init()
void RTC_Init (time_t seconds)
Initializes the API for the RTC.
Parameters
seconds seconds since 1/1/1970, 00:00:00 UTC
Definition at line 14 of file RTC.c.
References RTC_HalInit().
RTC_SetSeconds()
void RTC_SetSeconds (time_t seconds)
Updates the RTC to the new values passed to it in the form of seconds.
Parameters
seconds seconds since 1/1/1970, 00:00:00 UTC
Definition at line 30 of file RTC.c.
RTC_SetValue()
void RTC_SetValue (struct tm * dateTime)
Updates the RTC to the new values passed to it in the form of a date.
Parameters
dateTime pointer to a structure containing the date with which to update the clock
Definition at line 26 of file RTC.c.
References RTC_HalSetValue().