Embedded Systems: LCD
LCD
DRIVERS
Provides the core capabilities for the LCD.
Functions
void LCDText_Init (void)
Initializes the API for the LCD.
void LCDText_WriteChar (char ch)
Writes a char into the LCD.
void LCDText_WriteString (char *str)
Writes a string into the LCD.
void LCDText_SetCursor (int row, int column)
Locates the cursor.
void LCDText_Clear (void)
Clears the LCD.
void LCDText_Printf (char *fmt,...)
Printf like the one in the C library.
Detailed Description
Provides the core capabilities for the LCD.
Function Documentation
LCDText_Clear()
void LCDText_Clear (void)
Clears the LCD.
Parameters
does not have any entry parameters
Returns
none
Definition at line 153 of file LCD.c.
References DELAY_Stopwatch().
Referenced by addCard(), modoManutencao(), and modoNormal().
LCDText_Init()
void LCDText_Init (void)
Initializes the API for the LCD.
Parameters
does not have any entry parameters
Returns
none
Note
this function must be used before any other LCD function
Definition at line 73 of file LCD.c.
References PIN_settype().
LCDText_Printf()
void LCDText_Printf (char * fmt, ...)
Printf like the one in the C library.
Parameters
fmt : phrase to print
... : variables that will be printed its value
Returns
none
Definition at line 159 of file LCD.c.
References DELAY_Stopwatch(), and LCDText_WriteString().
Referenced by displayLog(), modoManutencao(), and modoNormal().
LCDText_SetCursor()
void LCDText_SetCursor (int row, int column)
Locates the cursor.
Parameters
row row to locate the cursor
column column to locate the cursor
Returns
none
Definition at line 142 of file LCD.c.
References LCDText_LINES.
Referenced by LCDText_WriteString().
LCDText_WriteChar()
void LCDText_WriteChar (char ch)
Writes a char into the LCD.
Parameters
ch char to be written into the LCD
Returns
none
Definition at line 123 of file LCD.c.
Referenced by LCDText_WriteString().
LCDText_WriteString()
void LCDText_WriteString (char * str)
Writes a string into the LCD.
Parameters
str string to be written into the LCD
Returns
none
Definition at line 129 of file LCD.c.
References DELAY_Stopwatch(), LCDText_SetCursor(), and LCDText_WriteChar().
Referenced by LCDText_Printf().