Embedded Systems: PINCONFIG
PINCONFIG
HAL
Provides the core capabilities for Pin configurations.
Functions
void PIN_settype (PinID_typedef id, int mode)
Selects and sets the mode of the pin which its Id was given.
Detailed Description
Provides the core capabilities for Pin configurations.
Function Documentation
PIN_settype()
void PIN_settype (PinID_typedef id, int mode)
Selects and sets the mode of the pin which its Id was given.
Parameters
id Pin which is to be selected and set a given mode
mode mode to be set to the given pin
Definition at line 19 of file pinconfig.c.
Referenced by ENCODER_Init(), LCDText_Init(), and SPI_Init().