Embedded Systems: RTCHAL
RTCHAL
HAL
Provides the core capabilities for the built-in RTC.
Functions
void RTC_Start (void)
Starts the in-built RTC.
void RTC_Stop (void)
Stops the in-built RTC.
void RTC_HalInit (void)
Initializes the in-built RTC.
void RTC_HalGetValue (struct tm *dateTime)
Gets the value of the RTC and puts into the struct given by the parameter.
void RTC_HalSetValue (struct tm *dateTime)
Sets the value of the RTC given by the entry parameter.
Detailed Description
Provides the core capabilities for the built-in RTC.
Function Documentation
RTC_HalGetValue()
void RTC_HalGetValue (struct tm * dateTime)
Gets the value of the RTC and puts into the struct given by the parameter.
Parameters
*dateTime Time structure that will serve to store the current time in which we find the RTC
Note
This function must be called prior to any other RTC functions
Definition at line 31 of file rtcHal.c.
Referenced by RTC_GetValue().
RTC_HalInit()
void RTC_HalInit (void)
Initializes the in-built RTC.
Parameters
does not have any entry parameters
Definition at line 23 of file rtcHal.c.
Referenced by RTC_Init().
RTC_HalSetValue()
void RTC_HalSetValue (struct tm * dateTime)
Sets the value of the RTC given by the entry parameter.
Parameters
*dateTime Time structure that will set the current time of the RTC
Definition at line 42 of file rtcHal.c.
Referenced by RTC_SetValue().
RTC_Start()
void RTC_Start (void)
Starts the in-built RTC.
Parameters
does not have any entry parameters
Definition at line 15 of file rtcHal.c.
RTC_Stop()
void RTC_Stop (void)
Stops the in-built RTC.
Parameters
does not have any entry parameters
Definition at line 19 of file rtcHal.c.
Referenced by setClock(), and setDate().