Embedded Systems: UTILS
UTILS
APP
Provides utils for the application.
Functions
int numDays (int year, int month)
Useful function to deal with the various calendar days scenarios.
void textCalendar (struct tm *dateTime)
Useful function write the Calendar text.
void textClock (struct tm *dateTime)
Useful function write the clock text.
void setDate (struct tm *dateTime)
Useful function to set the Date.
void setClock (struct tm *dateTime)
Useful function to set the clock.
Detailed Description
Provides utils for the application.
Function Documentation
numDays()
int numDays (int year, int month)
Useful function to deal with the various calendar days scenarios.
Parameters
year year to check its scenarios
month month to check its scenarios
Returns
the right number of days for the given month and year
Definition at line 44 of file utils.c.
setClock()
void setClock (struct tm * dateTime)
Useful function to set the clock.
Parameters
dateTime time struct that tells the function current time in the machine
Returns
none
Definition at line 239 of file utils.c.
References RTC_Stop().
setDate()
void setDate (struct tm * dateTime)
Useful function to set the Date.
Parameters
dateTime time struct that tells the function current time in the machine
Returns
none
Definition at line 97 of file utils.c.
References DELAY_GetElapsedMillis(), and RTC_Stop().
textCalendar()
void textCalendar (struct tm * dateTime)
Useful function write the Calendar text.
Parameters
dateTime time struct that tells the function what to print
Returns
none
Definition at line 58 of file utils.c.
References DELAY_GetElapsedMillis().
textClock()
void textClock (struct tm * dateTime)
Useful function write the clock text.
Parameters
dateTime time struct that tells the function what to print
Returns
none
Definition at line 79 of file utils.c.
References DELAY_GetElapsedMillis().