Embedded Systems: FLASH_DRIVERS
FLASH_DRIVERS
DRIVERS
Provides the core capabilities for the built-in FLASH.
Functions
unsigned int DRIVERS_FLASH_BlankCheck (unsigned int sector)
Runs the IAP routine with BlankCheck command (checks if the sector is blank)
unsigned int DRIVERS_FLASH_PrepareSector (unsigned int sector)
Runs the IAP routine with PrepareSector command (prepares the sector for write operations)
unsigned int DRIVERS_FLASH_EraseSector (unsigned int sector)
Runs the IAP routine with EraseSector command (erases the sector)
unsigned int DRIVERS_FLASH_WriteData (void *dstAddr, void *srcAddr, unsigned int size)
Runs the IAP routine with WriteData command (writes what you want where you want)
unsigned int DRIVERS_FLASH_VerifyData (void *dstAddr, void *srcAddr, unsigned int size)
Reads the state of the built-in LED and returns its logical value.
Detailed Description
Provides the core capabilities for the built-in FLASH.
Function Documentation
DRIVERS_FLASH_BlankCheck()
unsigned int DRIVERS_FLASH_BlankCheck (unsigned int sector)
Runs the IAP routine with BlankCheck command (checks if the sector is blank)
Parameters
sector Sector in which you wish to run the BlankCheck command
Returns
the error code that the IAP routine gave
Note
all of this is done by calling the function in flash.h of the HAL
Definition at line 15 of file DRIVERS_FLASH.c.
References FLASH_BlankCheck().
DRIVERS_FLASH_EraseSector()
unsigned int DRIVERS_FLASH_EraseSector (unsigned int sector)
Runs the IAP routine with EraseSector command (erases the sector)
Parameters
sector Sector in which you wish to run the EraseSector command
Returns
the error code that the IAP routine gave
Note
all of this is done by calling the function in flash.h of the HAL
Definition at line 26 of file DRIVERS_FLASH.c.
References FLASH_EraseSector().
DRIVERS_FLASH_PrepareSector()
unsigned int DRIVERS_FLASH_PrepareSector (unsigned int sector)
Runs the IAP routine with PrepareSector command (prepares the sector for write operations)
Parameters
sector Sector in which you wish to run the PrepareSector command
Returns
the error code that the IAP routine gave
Note
this function must be run before any write operations in the flash
Definition at line 21 of file DRIVERS_FLASH.c.
References FLASH_PrepareSector().
DRIVERS_FLASH_VerifyData()
unsigned int DRIVERS_FLASH_VerifyData (void * dstAddr, void * srcAddr, unsigned int size)
Reads the state of the built-in LED and returns its logical value.
Parameters
*dstAddr Address of the destination where I wish to write
*srcAddr Address of the source of what I wish to write
size Size of what I wish to write
Returns
the error code that the IAP routine gave
Note
all of this is done by calling the function in flash.h of the HAL
Definition at line 36 of file DRIVERS_FLASH.c.
References FLASH_VerifyData().
DRIVERS_FLASH_WriteData()
unsigned int DRIVERS_FLASH_WriteData (void * dstAddr, void * srcAddr, unsigned int size)
Runs the IAP routine with WriteData command (writes what you want where you want)
Parameters
*dstAddr Address of the destination where I wish to write
*srcAddr Address of the source of what I wish to write
size Size of what I wish to write
Returns
the error code that the IAP routine gave
Note
all of this is done by calling the function in flash.h of the HAL
Definition at line 31 of file DRIVERS_FLASH.c.
References FLASH_WriteData().